name: SampleApp_$(Date:yyyyMMDD)$(Rev:r)

trigger:
- Main
pool:  
  MVCLocalPool
steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    configuration: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)" '